In [1]:
import gym

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.


In [2]:
e = gym.make('CartPole-v0')

/opt/anaconda3/envs/RFlearning/lib/python3.9/site-packages/gym/envs/registration.py:555: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.warn(


In [ ]:
obs = e.reset() # 初始化
obs

(array([ 0.03892492, -0.04843795, -0.02642719, -0.0205427 ], dtype=float32),
 {})

In [7]:
e.action_space # 动作空间

Discrete(2)

In [8]:
e.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [ ]:
e.step(0) 

/opt/anaconda3/envs/RFlearning/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


(array([ 0.03795616, -0.24317114, -0.02683804,  0.2636864 ], dtype=float32),
 1.0,
 False,
 False,
 {})

In [14]:
e.action_space.sample()

1

In [16]:
e.observation_space.sample()

array([-1.1311204e-01, -1.5744203e+38, -1.0392498e-02,  5.8732696e+37],
      dtype=float32)